### ISSUE TITLE
Grpc error

### ISSUE THREAD

**Issue by CheneyHsu** [blockchain-monitoring/blockchain-monitoring#22]
I use blockchain-monitoring , please help me .  I debug Blockchain-monitoring container, fllow:

2017-08-11 08:02:26.814 WARN 7 --- [ main] o.b.fly_client_spring.utils.SampleStore : Could not find the file "/tmp/users.properties"2017-08-11 08:02:26.832 WARN 7 --- [ main] o.b.fly_client_spring.utils.SampleStore : Could not find the file "/tmp/users.properties"2017-08-11 08:02:26.890 INFO 7 --- [ main] o.b.fly_client_spring.FlyNet : INIT SUCCESS
2017-08-11 08:02:26.899 INFO 7 --- [ main] o.b.fly_client_spring.FlyNet : peer: peer0.org1.example.com
2017-08-11 08:02:26.939 INFO 7 --- [ main] o.b.fly_client_spring.FlyNet : peer: peer0.org2.example.com
2017-08-11 08:02:28.487 ERROR 7 --- [ main] o.b.config.GrafanaConfig : {"message":"Not found"}
2017-08-11 08:02:31.116 INFO 7 --- [ main] o.s.j.e.a.AnnotationMBeanExporter : Registering beans for JMX exposure on startup
2017-08-11 08:02:31.148 INFO 7 --- [ main] org.blockchain_monitoring.Application : Started Application in 15.642 seconds (JVM running for 17.413)
2017-08-11 08:02:33.264 WARN 7 --- [ault-executor-0] io.netty.util.internal.MacAddressUtil : Failed to find a usable hardware address from the network inte
rfaces; using random bytes: 32:e9:b4:23:4c:02:0d:6b
2017-08-11 08:02:33.501 ERROR 7 --- [pool-3-thread-1] org.hyperledger.fabric.sdk.Channel : Sending proposal to peer0.org1.example.com failed because of:
gRPC failure=Status{code=UNAVAILABLE, description=Channel closed while performing protocol negotiation, cause=null}

java.lang.Exception: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:2029) [fabric-sdk-java-1.0.0-rc1.jar!/:na]
at org.hyperledger.fabric.sdk.Channel.queryInstalledChaincodes(Channel.java:1770) [fabric-sdk-java-1.0.0-rc1.jar!/:na]
at org.hyperledger.fabric.sdk.HFClient.queryInstalledChaincodes(HFClient.java:427) [fabric-sdk-java-1.0.0-rc1.jar!/:na]
at org.blockchain_monitoring.fly_client.FlyClient.queryInstalledChaincodes(FlyClient.java:309) [fly-client-2.0.25.jar!/:na]
at org.blockchain_monitoring.scheduler.OrganisationMetricWriter.getPeerInfo(OrganisationMetricWriter.java:56) [classes!/:na]
at org.blockchain_monitoring.scheduler.OrganisationMetricWriter.accept(OrganisationMetricWriter.java:40) [classes!/:na]
at org.blockchain_monitoring.scheduler.OrganisationMetricWriter.accept(OrganisationMetricWriter.java:25) [classes!/:na]
at java.util.ArrayList.forEach(ArrayList.java:1249) [na:1.8.0_121]
at org.blockchain_monitoring.scheduler.ScheduledTasks.reportCurrentTime(ScheduledTasks.java:51) [classes!/:na]

**Comment by rafizanbaharum** [comment]
you can try "docker ps" to see if your peers are running
